package cn.com.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-08-05T21:36:18.817+08:00
 * Generated source version: 3.1.1
 * 
 */
@WebService(targetNamespace = "http://service.com.cn/", name = "IHelloWorld")
public interface IHelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.com.cn/", className = "cn.com.service.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.com.cn/", className = "cn.com.service.SayHelloResponse")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveHello", targetNamespace = "http://service.com.cn/", className = "cn.com.service.SaveHello")
    @WebMethod
    @ResponseWrapper(localName = "saveHelloResponse", targetNamespace = "http://service.com.cn/", className = "cn.com.service.SaveHelloResponse")
    public java.lang.String saveHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
